--Attempt of trainer for SK

require("strainerpointers")

--goto table
loadTable = {13,115,117,79,14,15,16,17,18,19,20,21,22,23,24,25,26,27,33,29,30,35,28,31,34,32,52,49,46,54,48,44,53,45,43,42,47,41,50,51,62,63,67,61,58,59,60,64,65,66,74,75,76,77,135,112,136,104,137,139,103,142,141,106,107,108,109,110,114,126,127,118,119,120,80,105,113,36,55,68,78,132,133,134,40,39,38,57,56,111,72,70,71,130,131,37,69}
bossWarpTable = {13,14,15,16,17,18,19,20,21,22,23,24,32,51,66,77,117,127}

--checkpoint position offset
checkpointOffset = 1.4


-- Minor functions for general use
setGlobalKeyPollInterval(100)

local function isempty(s)
  return s == nil or s == ''
end

function has_value (tab, val)
    for index, value in ipairs (tab) do
        if value == val then
            return true
        end
    end

    return false
end

function Round3(num)
         return math.floor(1000*num+0.5)/1000
end
function Round1(num)
         return math.floor(10*num+0.5)/10
end

function compareTopWindow()
         return getWindowProcessID(getForegroundWindow()) == getOpenedProcessID()
end

--Segment automatically generated by CE

function FormClose(sender)
         --before closing, undo code injection scripts
         writeInteger(varCameraLock,0)
         a = addresslist_getMemoryRecordByID(addresslist,400)
         memoryrecord_unfreeze(a)
         a = addresslist_getMemoryRecordByID(addresslist,402)
         memoryrecord_unfreeze(a)
         a = addresslist_getMemoryRecordByID(addresslist,20)
         memoryrecord_unfreeze(a)
         a = addresslist_getMemoryRecordByID(addresslist,11)
         memoryrecord_unfreeze(a)
         a = addresslist_getMemoryRecordByID(addresslist,485)
         memoryrecord_unfreeze(a)
         closeCE()
         return caFree --Possible options: caHide, caFree, caMinimize, caNone
end

gPlaySoundOnAction=false
STrainer.show()
addresslist=getAddressList()

--custom values for warps
customX = 0
customY = 0

--custom misc values
customHP = 0

gameIsAttached = false
function ReattachGame()
         if gameIsAttached then
            if readInteger(varGoto) == 453 then return true end
         end
         openProcess("ShovelKnight.exe")
         if readInteger(varGoto) == 453 then
            gameIsAttached = true
            setProperty(STrainer,"Caption","STrainer")
            assert = addresslist_getMemoryRecordByID(addresslist,20)
            memoryrecord_unfreeze(assert)
            memoryrecord_freeze(assert)
         else
             gameIsAttached = false
             setProperty(STrainer,"Caption","STrainer (not attached to game)")
         end
         return gameIsAttached
end


--Set warp with current Position
function setWarp1()
         if not ReattachGame() then return end
         if isempty(readFloat(varPosX)) then return end

         customX = Round3(readFloat(varPosX))
         customY = Round3(readFloat(varPosY))

         setProperty(STrainer.BCustomX,"Text",customX)
         setProperty(STrainer.BCustomY,"Text",customY)
end

--Sets warp with values on text boxes
function setWarp2()
         if isempty(readFloat(varPosX)) then return end

         customX = getProperty(STrainer.BCustomX,"Text")
         customY = getProperty(STrainer.BCustomY,"Text")
         setProperty(STrainer.BCustomX,"Text",Round3(customX))
         setProperty(STrainer.BCustomY,"Text",Round3(customY))
end

--Stores specified health value
function CEEdit1Change()
         customHP = tonumber(getProperty(STrainer.CEEdit1,"Text"))
         if isempty(customHP) then customHP = 1
         else customHP = math.floor(customHP) end
         if customHP > 20 or customHP < 0 then
            customHP = 0
         end
end


--Sets player's health
function KillRestart()
         if not ReattachGame() then return end
         if not compareTopWindow() then return end
         if isempty(readFloat(varHealth)) then return end
         --writeFloat(varHealth,1)
         if customHP == 0 then
            PlayerKillEnable()
            --stop the timer as well
             bossTimerActive = false
             bosscount = 0
             if getProperty(STrainerTimer,"Visible") then
                STrainerTimer.TimerText.Font.Color = 0xff0000
             end
         else
            writeFloat(varHealth,customHP)
         end

end

function KillRestartAlt()
         if isempty(readFloat(varHealth)) then return end
         --writeFloat(varHealth,1)
         if customHP == 0 then
            PlayerKillEnable()
            --stop the timer as well
             bossTimerActive = false
             bosscount = 0
             if getProperty(STrainerTimer,"Visible") then
                STrainerTimer.TimerText.Font.Color = 0xff0000
             end
         else
            writeFloat(varHealth,customHP)
         end
end

--Performs instant player warp
function ExecuteWarpNew()
         if not ReattachGame() then return end
         if not compareTopWindow() then return end
         if customX == 0 then return end
         local screen = readInteger(varStage)
         if not has_value(loadTable,screen) then return end

         writeInteger(varCheckRespawn,2)
         writeFloat(varCheckX,customX-checkpointOffset)
         writeFloat(varCheckY,customY-checkpointOffset)
         writeInteger(varIntro,screen)

         sleep(50)
         writeInteger(varGoto,screen)

         if getProperty(STrainerTimer,"Visible") then
            STrainerTimer.TimerText.Font.Color = 0xffffff
            bossTimerActive = true
            bosscount = 1
            bosstimer = 0
            setProperty(STrainerTimer.TimerText,"Caption","0:00.0")
            if screen == 23 then bosscount = 9 end
            if screen == 24 then
                 if readInteger(varCharacter) == 1 then bosscount = 3
                 else bosscount = 2 end
            end
            if screen == 19 then bosscount = 2 end
            if screen == 77 then bosscount = 3 end
         end
         setProperty(STrainer.bosskilltimer,"Enabled",getProperty(STrainer.CECheckbox2,"Checked") or getProperty(STrainerTimer,"Visible"))
end

--Performs warp to boss, based on current stage
--For 3.0A, old values are incremented by 3
function ExecuteBossWarp()
         if not ReattachGame() then return end
         if not compareTopWindow() then return end
         screen = readInteger(varStage)
         if not has_value(bossWarpTable,screen) then return end

         writeInteger(varCheckRespawn,2)
         writeInteger(varIntro,screen)
         if screen == 13 then --Plains
            writeFloat(varCheckX,722.885)
            writeFloat(varCheckY,-406)
         end
         if screen == 14 then --Pridemoor Keep
            if readInteger(varCharacter) == 2 then --specter knight
               writeFloat(varCheckX,818.58)
               writeFloat(varCheckY,-202)
            else
               writeFloat(varCheckX,760.98)
               writeFloat(varCheckY,-199)
            end
         end
         if screen == 15 then --Lich Yard
            if readInteger(varCharacter) == 2 then --specter knight
               writeFloat(varCheckX,939.7)
               writeFloat(varCheckY,-120)
            else
               writeFloat(varCheckX,925)
               writeFloat(varCheckY,-121)
            end
         end
         if screen == 16 then --Explodatorium
            if readInteger(varCharacter) == 2 then --specter knight
               writeFloat(varCheckX,989)
               writeFloat(varCheckY,-195)
            else
               writeFloat(varCheckX,974)
               writeFloat(varCheckY,-195)
            end
         end
         if screen == 17 then --Iron Whale
            if readInteger(varCharacter) == 2 then --specter knight
               writeFloat(varCheckX,756.367)
               writeFloat(varCheckY,-254)
            else
               writeFloat(varCheckX,844.22)
               writeFloat(varCheckY,-213)
            end
         end
         if screen == 18 then --Lost City
            if readInteger(varCharacter) == 2 then --specter knight
               writeFloat(varCheckX,807.53)
               writeFloat(varCheckY,-396)
            else
               writeFloat(varCheckX,885.8)
               writeFloat(varCheckY,-258)
            end
         end
         if screen == 19 then --Clockwork Tower
            if readInteger(varCharacter) == 2 then --specter knight
               writeFloat(varCheckX,682.584)
               writeFloat(varCheckY,-207)
            else
               writeFloat(varCheckX,642.46)
               writeFloat(varCheckY,-251)
            end
         end
         if screen == 20 then --Stranded Ship
            if readInteger(varCharacter) == 2 then --specter knight
               writeFloat(varCheckX,1029.784)
               writeFloat(varCheckY,-157)
            else
               writeFloat(varCheckX,909.66)
               writeFloat(varCheckY,-94)
            end
         end
         if screen == 21 then --Flying Machine
            if readInteger(varCharacter) == 2 then
               writeFloat(varCheckX,828.184)
               writeFloat(varCheckY,-94)
            else
                writeFloat(varCheckX,933.66)
                writeFloat(varCheckY,-74)
            end
         end
         if screen == 22 then --Tower1
            if readInteger(varCharacter) == 2 then --specter knight
               writeFloat(varCheckX,1084.184)
               writeFloat(varCheckY,-195)
            else
               writeFloat(varCheckX,1044.3)
               writeFloat(varCheckY,-117)
            end
         end
         if screen == 23 then --Tower2
            if readInteger(varCharacter) == 1 then --plague knight
               writeFloat(varCheckX,679.243)
               writeFloat(varCheckY,-186)
            else
               writeFloat(varCheckX,679.243)
               writeFloat(varCheckY,-186)
            end
         end
         if screen == 24 then --Tower3
            if readInteger(varCharacter) == 2 then --specter knight
               writeFloat(varCheckX,237.976)
               writeFloat(varCheckY,-35)
            else
               writeFloat(varCheckX,440.99)
               writeFloat(varCheckY,-193)
            end
         end
         if screen == 117 then --Tower hub for specter
            writeFloat(varCheckX,234)
            writeFloat(varCheckY,-141)
         end
         if screen == 127 then --flashback 2
            writeFloat(varCheckX,241.02)
            writeFloat(varCheckY,-35)
         end
         if screen == 32 then --Grand Hall
            writeFloat(varCheckX,453.8)
            writeFloat(varCheckY,-197)
         end
         if screen == 51 then --Royal Pond
            writeFloat(varCheckX,697)
            writeFloat(varCheckY,-134)
         end
         if screen == 66 then --King's Roost
            writeFloat(varCheckX,784.98)
            writeFloat(varCheckY,-321)
         end
         if screen == 77 then --King Tower 4
            writeFloat(varCheckX,444.08)
            writeFloat(varCheckY,-157)
         end

         --trigger stage loading
         sleep(50)
         writeInteger(varGoto,screen)

         if getProperty(STrainerTimer,"Visible") then
            STrainerTimer.TimerText.Font.Color = 0xffffff
            bossTimerActive = true
            bosscount = 1
            bosstimer = 0
            setProperty(STrainerTimer.TimerText,"Caption","0:00.0")
            if screen == 21 then bosscount = 9 end
            if screen == 22 then
                 if readInteger(varCharacter) == 1 then bosscount = 3
                 else bosscount = 2 end
            end
            if screen == 17 then bosscount = 2 end
            if screen == 77 then bosscount = 3 end
            if screen == 109 then bosscount = 2 end
         end
         setProperty(STrainer.bosskilltimer,"Enabled",getProperty(STrainer.CECheckbox2,"Checked") or getProperty(STrainerTimer,"Visible"))


end

--Toggle camera lock pointer
--Uncomment once varCameraLock pointer is found
--function CameraUnlock()
--         if not ReattachGame() then return end
--         if getProperty(STrainer.CECheckbox1,"Checked") then
--            writeInteger(varCameraLock,1)
--            cameralock = addresslist_getMemoryRecordByID(addresslist,423)
--            memoryrecord_freeze(cameralock)
--
--         else
--            writeInteger(varCameraLock,0)
--            cameralock = addresslist_getMemoryRecordByID(addresslist,423)
--            memoryrecord_unfreeze(cameralock)
--        end
--end


function ToggleUnlimitedMana()
         if not ReattachGame() then
            setProperty(STrainer.CECheckbox3,"Checked",false)
            return end
         local mana = addresslist_getMemoryRecordByID(addresslist,11)
         if getProperty(STrainer.CECheckbox3,"Checked") then
            memoryrecord_freeze(mana)
         else
            memoryrecord_unfreeze(mana)
         end
end


--Directly freezes mana value instead of using script
function ToggleUnlimitedManaAlt()
         if not ReattachGame() then
            setProperty(STrainer.CECheckbox3,"Checked",false)
            return end
         local mana = addresslist_getMemoryRecordByID(addresslist,485)
         if getProperty(STrainer.CECheckbox3,"Checked") then
            memoryrecord_freeze(mana)
         else
            memoryrecord_unfreeze(mana)
         end
end


function TriggerScreen()
         if not ReattachGame() then return end
         local x = getProperty(STrainer.CEComboBox1,"ItemIndex") + 1
         local y = readInteger(varCharacter)
         x = loadTable[x]

         if CharacterWarning(x,y) then
            showMessage("This character and area combination will cause a game crash, so it won't be executed.")
            return end

         writeInteger(varGoto,x)
         if getProperty(STrainerTimer,"Visible") then
            STrainerTimer.TimerText.Font.Color = 0xffffff
            bossTimerActive = true
            bosscount = 1
            bosstimer = 0
            setProperty(STrainerTimer.TimerText,"Caption","0:00.0")
            if x == 21 then bosscount = 9 end
            if x == 22 then
                 if readInteger(varCharacter) == 1 then bosscount = 3
                 else bosscount = 2 end
            end
            if x == 17 then bosscount = 2 end
         end
         setProperty(STrainer.bosskilltimer,"Enabled",getProperty(STrainer.CECheckbox2,"Checked") or getProperty(STrainerTimer,"Visible"))
end


function CharacterWarning(x,y)
         --if (x == 37 or x == 38) and y ~=2 then return true end
         if ((x <= 24 or x>= 115) and y == 3) then return true end
         if ((x == 23 or x == 131 or x == 132 or x == 135 or x == 136 or x == 137 or x == 142) and y == 2) then return true end
         if (x == 107 and y == 1) then return true end
         if (x == 108 or x == 109) then return true end
         if ((x == 79 or x == 33 or x == 35 or x == 34 or x == 52 or x == 54 or x == 53 or x == 67 or x == 80 or x == 105 or x == 40 or x == 39 or x == 38 or x == 57 or x == 72 or x == 71 or x == 114) and y ~= 3) then return true end

         return false
end


--Uncomment once varCameraLock pointer is found
--function ToggleCameraLock()
--         setProperty(STrainer.CECheckbox1, "Checked", not getProperty(STrainer.CECheckbox1,"Checked"))
--         CameraUnlock()
--end


function SetMoney()
         if not ReattachGame() then return end
         local x = getProperty(STrainer.CEEdit2,"Text")
         if isempty(x) then return end
         x = tonumber(x)
         if isempty(x) then return end
         if x < 0 then return end
         writeInteger(varMoney,math.floor(x))
end


function BossHealth()
         if not ReattachGame() then return end
         writeFloat(varBossHealth,1)
end


function PlayerKillEnable()
         --enable player kill script
         playerkill = addresslist_getMemoryRecordByID(addresslist,400)
         memoryrecord_freeze(playerkill)
         setProperty(STrainer.playerkilltimer,"Enabled",true)
                     --stop the timer as well
         if bossTimerActive then
             bossTimerActive = false
             bosscount = 0
             if getProperty(STrainerTimer,"Visible") then
                STrainerTimer.TimerText.Font.Color = 0xff0000
             end
         end
end


function PlayerKillDisable()
         --disable part of player kill script
         playerkill = addresslist_getMemoryRecordByID(addresslist,400)
         memoryrecord_unfreeze(playerkill)
         setProperty(STrainer.playerkilltimer,"Enabled",false)
end


function ToggleBossKill()
         if not ReattachGame() then return end
         bosskill = addresslist_getMemoryRecordByID(addresslist,402)
         if getProperty(STrainer.CECheckbox2,"Checked") then
            memoryrecord_freeze(bosskill)
            --setProperty(STrainer.bosskilltimer,"Enabled",true)
            bossHealthOld = 0
         else
            memoryrecord_unfreeze(bosskill)
            --setProperty(STrainer.bosskilltimer,"Enabled",false)
         end
         setProperty(STrainer.bosskilltimer,"Enabled",getProperty(STrainer.CECheckbox2,"Checked") or getProperty(STrainerTimer,"Visible"))

end

bosstimer = 0
bosscount = 0
bossHealthOld = 0
bossTimerActive = false
function CheckBossKill()
         --update timer
         if getProperty(STrainerTimer,"Visible") and bossTimerActive then
            bosstimer = bosstimer + 1
            local t1 = bosstimer % 10
            local t2 = math.floor(bosstimer/10)
            local t3 = math.floor(t2/60)
            t2 = t2 % 60
            if t2 < 10 then t2 = "0" .. t2 end
            setProperty(STrainerTimer.TimerText,"Caption",t3 .. ":" .. t2 .. "." .. t1)
         end

         local bossHealth = readFloat(varBossHealth)
         --check for kill condition
         if isempty(bossHealth) then return end
         if bossHealthOld > 0 and bossHealth == 0 then
            if getProperty(STrainer.CECheckbox2,"Checked") then
               PlayerKillEnable()
               bosscount = 0
            end
            if getProperty(STrainerTimer,"Visible") then
               bosscount = bosscount - 1
               if bosscount <= 0 then
                 bossTimerActive = false
                 STrainerTimer.TimerText.Font.Color = 0xff0000
               end
            end
         end
         bossHealthOld = bossHealth

end

function OpenTimer()
         bossTimerActive = false
         bosstimer = 0
         bosscount = 0
         setProperty(STrainerTimer.TimerText,"Caption","0:00.0")
         STrainerTimer.show()
end


HKey = {}
HKey[1] = createHotkey(ExecuteWarpNew,VK_F1)
HKey[2] = createHotkey(ExecuteBossWarp,VK_F2)
HKey[3] = createHotkey(KillRestart,VK_F6)
HKey[4] = createHotkey(TriggerScreen,VK_F7)
HKey[5] = createHotkey(setWarp1,VK_F3)
--uncomment the next lines and change F3/F5/F8 to your key of choice to have a hotkey for money/boss kill
--HKey[5] = createHotkey(ToggleCameraLock,VK_F8)
--Hkey[6] = createHotkey(SetMoney,VK_F3)
--Hkey[7] = createHotkey(ToggleBossKill,VK_F5)
for i = 1, #HKey do setProperty(HKey[i],"DelayBetweenActivate",500) end

ReattachGame()
